### ISSUE TITLE
Implementing the methods get user follows and followers

### ISSUE THREAD

**Issue by onurozmenn** [dmytrostriletskyi/threads-net#12] opened 2023-07-08 14:28 UTC
If you add these functions that will be great. I tried but I can get only Instagram followers.

**Comment by PittCaleb** [comment] 2023-07-08 20:29
Is this not a duplicate of issue #10?

**Comment by onurozmenn** [comment] 2023-07-09 01:02
Oh sorry about that. I didnt see. Should i delete this issue?

**Comment by onurozmenn** [comment] 2023-07-09 01:02
Oh sorry about that. I didnt see. Should i delete this issue?

**Comment by dmytrostriletskyi** [comment] 2023-07-09 09:44
Duplicate of https://github.com/dmytrostriletskyi/threads-net/issues/10

**Closed by dmytrostriletskyi** 2023-07-09 09:44 UTC
Labels: enhancement
