### ISSUE TITLE
How to find post id?

### ISSUE THREAD

**Issue by abolphazl** [dmytrostriletskyi/threads-net#11] opened 2023-07-08 13:03 UTC
Thank you for starting this awesome project
How can I access the post ID?

**Comment by FastFingertips** [comment] 2023-07-08 13:27
```py
import requests
def find_post_id_by_url(url):
    response = requests.get(url)
    response_text = response.text
    find_string = '3141737961795561608'
    if find_string in response_text: print("Found!")
    else: print("Not found!")
    
    """
    PARSİNG AND RETURN
    """

find_post_id_by_url('https://www.threads.net/t/CuZsgfWLyiI/')
```

**Comment by FastFingertips** [comment] 2023-07-08 13:37
Updated;
```py
def find_post_id_url(url):
    """
    Retrieves the post ID from a given URL by making a GET request and parsing the response.

    Args:
        url (str): The URL of the post.

    Returns:
        str: The post ID.

    Raises:
        requests.exceptions.RequestException: If there was an error during the request.
        ValueError: If the post ID was not found in the response.

    """
    response = requests.get(url)
    response_text = response.text

    find_string = '{"post_id":"'
    start = response_text.find(find_string) + len(find_string)
    end = response_text.find('"}', start)

    if start == -1 or end == -1:
        raise ValueError("Post ID not found in the response.")

    post_id = response_text[start:end]
    return post_id


post_id = find_post_id_url('https://www.threads.net/t/CuZsgfWLyiI/')
print("Post ID: " + post_id)
post = threads.get_post(post_id)
```

**Comment by abolphazl** [comment] 2023-07-08 14:02
Thank you.

**Comment by dmytrostriletskyi** [comment] 2023-07-09 09:45
Let's keep it open so we keep track of the feature we shall add into the library.

**Comment by dmytrostriletskyi** [comment] 2023-07-09 09:51
Duplicate of https://github.com/dmytrostriletskyi/threads-net/issues/5

**Closed by dmytrostriletskyi** 2023-07-09 09:51 UTC
Labels: enhancement, feature-request
